apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
  namespace: home-assistant
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: postgres-storage
  volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: home-assistant-cnpg-main-1-wal
  restartPolicy: Never
