apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uF9liIpxwYRPDyxFLXf0k2bbF7qbJEcDAqupANjLTqMtiq1kyOUUBVaDZgfel+/idwMwYjIkRKwnfZg2Va18iY1pIkTMGFpFLI1j5op9ap1or/TJSBk+4X/DcAQQNxZb590tXbttc53+ua2YFuf356xq8/Rnc76HaLdxnSjuWxqF9e++dUE4OIGZanPngFPeaDI4GH5rJVwoP3Ax0xSTk0AjKmRseu8x1kVcpFNgoiVsEdFm+1vTDDNSA4DE57FnrLiOcLutBQwrR3NrffvzyOob2zdrISIDZcrjlc/m02Dra11C84NtAgpCSgBMdvf3qx9PyCtmtYdpCajhJVB1sI/qxLID/T/zEy/dAXC01Z0KCSwMe//byScmEzS9zSZk,iv:rJ7ijSAn+IEmfuFi8ixKIZFxzyuVG2RlM+u0F46WAQs=,tag:l3336NNfUBDCBOeau9K1Mw==,type:str]
    identity.pub: ENC[AES256_GCM,data:97gwXeNzlExAgeC3ne5iKWkffNFafWPKnlUia3o9WCGIWkdM+evbczl8TITmc5V/LjkO5LWXlhwAY0Srep0XAdloz6nlFFazc1YXybecc47VNBJOBSPKxsRF4D1v0kMLO+YifZj2LujDzsrpgUTcOmFIkVvdtfXFVQY/GbAZszEYYU4STWHZnA9hiFzevRfzGWFOWmcpfn5uNgyox/X7lpewZpwrcOItY+e5JIlhRX7iZM3nZOXZyBBwW/v2ul8UHpAnyijrWKGevbsw8Q==,iv:3oHBmOplfeGLRdVfKst6mlX96VX2Y0/HUotprWSJnNs=,tag:lEi7wdzaFFiqSRVpOwFicQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:6reYXS2VV3oaasHqPwUiYACeUdhvbhgjGcByuXk+qLI2I30JvoI4qg6qnfpEB9ah7LcRAWW/IQNojQ0M116jCnptnUTz7AxvlqP6S8yrbqNmLrc5Kbx8J74p7DRUsIkl08jjHzLnwTOxTJ0dcThIxHVEV9P24Z9NdvbGTThMMvqoDei3Fn8VH1C0FyBY9nskaGdg+YmYWMLUUpwY2WtjaHUKzJPqvG4Qb3wd,iv:HiHtCEsFHyqjW0NK146DWuGkTgtMTeZ3T80BRqWLIEI=,tag:2t2w8GziYIgH4kDYdvlkHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c3sr6exe6w6vrc5kcpmcelru8emj5ppkvc9dtmh84jp22pnm5v5qm8cm75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bC9uaDlTR1ZzUytreFFl
            SS9uM0VNdXpRTlR3WWFrNkUxZG1DMUorVG1NCmsxNWRJRFdCNjBnNC93NWRLc25B
            amQ1M3QzZisxMFZjYXB1K3pXcVVlSWsKLS0tIEJMeUZENUtyZzhFS3N2Ni8vWEl4
            Z2FGa0tjSVQvODRtOElLTVVxNURuL2sKvOd88J6iB9/zbAzZonnew1F7J/CJ4NNp
            /JSNP8fP6bh15ieb3bounOfpYrBjYEXiocqsSxyPhcRFVd2+g1m0YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T18:15:37Z"
    mac: ENC[AES256_GCM,data:FbXER6llO/Vc/GDF8FyQiR7dWKcV0ITb5LS0wL3SoU7FCmzO+jV2SJmiGR4gkJGjIYXzjFaux+7bOh6Rb31BMV9vIGyaNPxsHcuMwgWF2E2st7mS8FGN7aKV257JS8ucwAqqOEgMVNpZDEl2iIPlMtisYkxis833AjeU2BWfuhw=,iv:1gBzCZTNF0tLMpSEF2EyyzQosdz2jsBHfXdNTW9IJx0=,tag:e1tK9oAJRcrZA71v0OHsWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
