apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5tTL9+tE+huPoZrsCQsO39cvFWfYpE7kX65NfDqDfIrnLyDws3cOJuiwLE9AWybgHoQToDxajJRTIGRAB5sRCHjGRv8vjDxAmspClGKXKGFlgeuYkQHkznq956lrXHqvU3nQi081pl9Oas079bCh+H6suqmnGmr5f0ZQoLVD4hINZGYh4GJKnbFB6wEYaYtBJnwsrMWDP6f582RHAMjN6zCYFqyEDGK6nQorE9I3aaF3jxA8jgsZ/dduc9Dd2BsgibltK9fYvDhn7B6C/zs2rEL9H/rIEtD/+ZQSGVOqwHX/Xz1upNQqZo3kx6GSQJr01eI4GLSKAYk+yU6oYB7V1Te1xC1Y4WSfLys7Ier875gulwHzbH4l7784GWO63xl+,iv:gWEAQ1mGJ1naOEqOLAWgHAOax3rHf/jT/5y/C7DS0Sk=,tag:Sdso/DbOVNBwmmOrPPOGrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:boO8HnOfzfCXOWsv6uLYknYgtXuP2NoIZjCTaFoTC8RS+HoFj/QOyhy/mn21iLXksIV7oVsRHBT1Y1ML89Bpj4BEph9kpGBHmwOWjBYISSYcy05BSDGRS3fshbZYtXz99gW17pDvbe0SUMnakylKneDUjZxUdLNUurLWFZvHcFxtELji5rBh/G3tdHs29G0l9xmNWcj3MHfmRIy8nB1uC+TcRi/RwFVTi3PhWAF1rLagq04OIIsFzd+ODu8DXz4qpqp9mwFgmJ8SSclq5w==,iv:d5rJFJ77wnAjJdimj07U79yU2eXhyUIWO1kQmRLykfA=,tag:S1Dd1MW7e9PX/LIUV+vLEQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:3RsC8l4uZS811cN2hJAxVQ9INr43U/P4atvlBWWFyr60xjGWwrkK2jpHdXsxR+NSZMTFTmQTGmomiMDCaBrHeR+8ZHQIVNpSkPtRlFWcW+xi7VDZNQbmZkRdoU+/4ZD0QmAHmppOgfWAv/AEKXxJIPmtAu4OnP0Df58qr+x9QWhGIhjQ9oHKfDjv00LOH7YVagW2byJ92cyi28UTuiXLF3Ysy665m6R6XQpr,iv:dZb+OQXX4KnIDBqyGR7LTl9j46axh3Du9wvei/tfsgE=,tag:tkPO4MeZUoUMZjqha4wpAw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c3sr6exe6w6vrc5kcpmcelru8emj5ppkvc9dtmh84jp22pnm5v5qm8cm75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMekVVSWQyVWJJNXJ1eDM2
            dFdvVXlic3NFSE13VWlFbzJzV3lYZm52c0gwCkVab01OcEVPN2lFTUsreldtMTRm
            YktiUUlaUlIxRWtGVUxGWFd5UWkwcGcKLS0tIGk4bUVwTW1FbTJydTk2cERsU2Ns
            WU44Uis2ZWlpT3RsTVBqM2tJcjBKQ28KzrFNZYjJgKHfKlTmkXFBueeQVr1UMsrv
            ozZjaXn2tahhxKAIOhxkPBG3Yxgf0AsnRmJYvLWJciw5OBJAlbBiUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T15:31:32Z"
    mac: ENC[AES256_GCM,data:tAYpDYx0sqcJC8zb+klliMnadhXiHkaNnBSaQxpC3E+5s7jSB7tUwrQwRULebDzRBU29y5DRtrgOS5SUIp5uFzBtCcmqB2Zhyeju7+hh1Gh42LSVl8VjfZAZSr1We2alWL+Wn+YCAvrAbZvPdhI4TUlgMrdHQNSpNIYPi69thOg=,iv:bH8sVtZ5dJXLy0lXUtacroviLeLFYCh3VugLE0sWU8A=,tag:azXEkNZoL9M82VdKoo3mmw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
