apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nGN3bsWaxWv0pnMK7IbGs5KDD8hGA92SdRNZ0OJAuMBwL5Rk7+imZZgu2Cwhlq/AmEf/BRBEngT8A4l0X3etWZm+EQMYBpWoWFOBkUxGwN4X80vLxebyAn95JX+/xalXkjZJTPZkWFF9ySAMmQfGMyZ9JAW1Tkp44lSisZQvh5t0z7C3z4MPXHPimGDc4n83lyw9hZcMwOonOBUdUFFEKlVqfMVK62OWPKYk+0Rt/pya1YP/mW2V0Ifr4OATtKqE7CylLzyNk663PX4TYnDRzLShRhge2MNVIbItVIdGgamkYOE5Wq7qsNhxT5tfCe7Y1te9ytsjeKcw2nwQOmWPKhlHL3XMdVGvmUO2XwNhQeoY2FrmqmbuZKjYM/ndK6dy,iv:v6HqIfMKjSnZ9Zqa2T4FCtu/wR4NrHPWbUDwMVLra6c=,tag:dj7fkAdLXqMj4SEOOLuUpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:MqcQ6OrPPlJTcANp1ctXn+6qFTIeWJshEDeEXbDbr/SHyTuSgoblyVrlc/jZ8Jnc8kAR1qTBp2j+7S0tUVGQNlj1RCCUB20i8c9+f0LMj0Wo8kxZ6A90cQzS1lsmAeTMB2KlmHf1lm0/iLSHi8MAnSVS/07MgJ1zeUh4Cfb66bLnA9EvTrLXhVPY3RAV1JrmAa8ABuyJz8/iVEJBvLxyo6rfXb1F1mKgDW3Vz5swxCupqKeia3uYD5bLK+qVcjyRlhLdhfBJOu4FsFJ6mg==,iv:tMRDterAGUo68dIRkt8MZiFsFqd6F9Q1qiAQ+vl6N+k=,tag:JILV4cVtm8VngD3UPQ1omA==,type:str]
    known_hosts: ENC[AES256_GCM,data:AVMLk7WIi+c7ZXWdXJSGI0OB14QUFzRBjghtHOmV2UQglUAmnutxG2STi9ShqHrO+00qp4utDWY+bCqIPwFvH9G/l/0iXBSbDeDP89XIGPDtokL5YcSSrO4pynx6J1pIeVk39EJimgWOSvmWUV4DgXtllpKhoRGnGrlN4ig+1bD4dvYadohX86mRuksPqIryK5qgnBnhMIIVxsixnlnphupBQn1Oqj9fLoVv,iv:w4Z6lruOxu0Y58wkikczCowoHdBHEXAzPooGYMrdvTQ=,tag:/kVkAMk/6ApP4I5r4EP2WQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c3sr6exe6w6vrc5kcpmcelru8emj5ppkvc9dtmh84jp22pnm5v5qm8cm75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1NsV01qMzQ1Z3Brb2xE
            Z2lpNGJJU2dRWEkvMEFSb0NvL0R5ZmRJWjFJCnBDMjFKeUpoeGZXTE1mc0hoUlFq
            ZG1md05HWEk4QjdGdkJ5SmRxYlo3LzgKLS0tIExsS3owbFpRMDVxQXNVT3JuVVVW
            TTVIbTZFT21UeFQ4UkVEZERJa0g2MkUKQ32UXDGEc23jvBVs7T1XfRfRDfb1xOTX
            J9YBZCN5Mtrl0H++DvLrXWukoSFsv07/1s4WZY4ReSdumf3s0M172g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T21:16:09Z"
    mac: ENC[AES256_GCM,data:ltBO1UXFEnnj5yyaaJp+8Q2cAzChSAGunZj4nxbECRZNDRVFwOEvlliZwMCUdX9aT6jZXwDK+netCyNkHZ7Hv1tjt6OWvgWO0TrDThW8NomXBQIGIhfCGBMhzdZ2W7Or4i1XAvOE9yalM+cpGTJNbkZIZCcYKrI+n3tTESNmwOk=,iv:U+16UhYgfiLF+bboR4/D0I/PowgApDT12pcRMULWu5A=,tag:B9HXiZxlkYzRXKSGSnOU0A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
