apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: xteve
    namespace: xteve
spec:
    interval: 15m
    chart:
        spec:
            chart: xteve
            version: 15.3.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: xteve
    values:
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        persistence:
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: aws
                      type: restic
                      name: xteve-config
                      src:
                        enabled: true
                      dest:
                        enabled: true
        release_name: xteve
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 34400
                        targetPort: 34400
                type: LoadBalancer
                loadBalancerIP: 10.0.0.215
